/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.utesa.sistemaoperativo.sistemaarchivos.formularios;

import edu.utesa.sistemaoperativo.sistemaarchivos.Dto.Dto_Persona;
import edu.utesa.sistemaoperativo.sistemaarchivos.entidades.Persona;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Eduardo Liz
 */
public class cns_persona extends javax.swing.JDialog {

    /**
     * Creates new form cns_persona
     */
    
    File file;
    Persona persona;
    public cns_persona(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        persona = new Persona();
        file = new File(persona.getPath_persona());
        txtNombre.setEnabled(true);
    }
    
    public cns_persona() {
        initComponents();
        persona = new Persona();
        file = new File(persona.getPath_persona());
        txtNombre.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table_persona = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        table_persona.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        table_persona.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_personaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_persona);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Buscar por Nombre:");

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton5.setText("Buscar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void table_personaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_personaMouseClicked
        // TODO add your handling code here:
        Persona per = new Persona();
        per.setId_persona(Integer.parseInt(table_persona.getModel().getValueAt(table_persona.getSelectedRow(), 0).toString()));
        per.setNombre(table_persona.getModel().getValueAt(table_persona.getSelectedRow(), 1).toString());
        per.setApellido(table_persona.getModel().getValueAt(table_persona.getSelectedRow(), 2).toString());
        per.setDireccion(table_persona.getModel().getValueAt(table_persona.getSelectedRow(), 3).toString());
        per.setTelefono(table_persona.getModel().getValueAt(table_persona.getSelectedRow(), 4).toString());
        Dto_Persona.setPersona(per);
        this.dispose();
    }//GEN-LAST:event_table_personaMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        ArrayList<Persona> listfiltrada = new ArrayList<Persona>();
        ArrayList<Persona> list = new ArrayList<Persona>();

        try {
            list = persona.getListaPersona(file);
        } catch (IOException ex) {
            Logger.getLogger(cns_persona.class.getName()).log(Level.SEVERE, null, ex);
        }

        for(Persona tp : list){
            if(tp.getNombre().startsWith(txtNombre.getText()) || txtNombre.getText().isEmpty()){
                listfiltrada.add(tp);
            }
        }
        consultPersona(listfiltrada);
    }//GEN-LAST:event_jButton5ActionPerformed

    public void consultPersona(ArrayList<Persona> list){
        DefaultTableModel modelo = new DefaultTableModel();
        
        String [] cols = {"id","nombre","apellido","direccion","telefono"};
        for (int i=0;i<cols.length;i++)
            modelo.addColumn(cols[i]);
        
        int k;
       
        for(Persona ori : list){
             k=0;
                Object[] fila = new Object[5];
                fila[k++]=(Object)ori.getId_persona();
                fila[k++]=(Object)ori.getNombre();
                fila[k++]=(Object)ori.getApellido();
                fila[k++]=(Object)ori.getDireccion();
                fila[k++]=(Object)ori.getTelefono();
                modelo.addRow(fila);
        }    
            
        
        table_persona.setModel(modelo);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cns_persona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cns_persona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cns_persona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cns_persona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                cns_persona dialog = new cns_persona(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_persona;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
