/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.utesa.sistemaoperativo.sistemaarchivos.formularios;

import edu.utesa.sistemaoperativo.sistemaarchivos.Dto.Dto_TipoCuenta;
import edu.utesa.sistemaoperativo.sistemaarchivos.entidades.Cuenta;
import edu.utesa.sistemaoperativo.sistemaarchivos.entidades.Tipo_cuenta;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author juanlht
 */
public class cns_tipo_cuenta extends javax.swing.JDialog {

    /**
     * Creates new form cns_tipo_cuenta
     */
    File file;
    Tipo_cuenta tipo_c;
    
    
     public cns_tipo_cuenta(javax.swing.JDialog parent, boolean modal ) {
        super(parent, modal);
        initComponents();
        tipo_c = new Tipo_cuenta();
        file = new File(tipo_c.getPath_tipo_cuenta());
        txtTipo.setEnabled(true);
        
    }
     
    public cns_tipo_cuenta() {
        initComponents();
        tipo_c = new Tipo_cuenta();
        file = new File(tipo_c.getPath_tipo_cuenta());
        txtTipo.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabletipo_cuenta = new javax.swing.JTable();
        txtTipo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setAlwaysOnTop(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Buscar por nombre de tipo");

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton5.setText("Buscar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        tabletipo_cuenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabletipo_cuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabletipo_cuentaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabletipo_cuenta);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(20, 20, 20)
                        .addComponent(txtTipo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton5)
                            .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        ArrayList<Tipo_cuenta> listfiltrada = new ArrayList<Tipo_cuenta>();
        ArrayList<Tipo_cuenta> list = new ArrayList<Tipo_cuenta>();
        
        try {
            list = tipo_c.getLista(file);
        } catch (IOException ex) {
            Logger.getLogger(cns_tipo_cuenta.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        for(Tipo_cuenta tp : list){
            if(tp.getDescripcion().startsWith(txtTipo.getText()) || txtTipo.getText().isEmpty()){
                listfiltrada.add(tp);
            }
        }
        consultTipoCuenta(listfiltrada);
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void tabletipo_cuentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabletipo_cuentaMouseClicked
        // TODO add your handling code here:
        Tipo_cuenta tp = new Tipo_cuenta();
        tp.setId_tipo_cuenta(Integer.parseInt(tabletipo_cuenta.getModel().getValueAt(tabletipo_cuenta.getSelectedRow(), 0).toString()));
        tp.setTipo(tabletipo_cuenta.getModel().getValueAt(tabletipo_cuenta.getSelectedRow(), 1).toString());
        tp.setDescripcion(tabletipo_cuenta.getModel().getValueAt(tabletipo_cuenta.getSelectedRow(), 2).toString());
        Dto_TipoCuenta.setTipo_cuenta(tp);
        this.dispose();
    }//GEN-LAST:event_tabletipo_cuentaMouseClicked

    public void consultTipoCuenta(ArrayList<Tipo_cuenta> list){
        DefaultTableModel modelo = new DefaultTableModel();
        
        String [] cols = {"id","tipo","descripcion"};
        for (int i=0;i<cols.length;i++)
            modelo.addColumn(cols[i]);
        
        int k;
       
        for(Tipo_cuenta ori : list){
             k=0;
                Object[] fila = new Object[3];
                fila[k++]=(Object)ori.getId_tipo_cuenta();
                fila[k++]=(Object)ori.getTipo();
                fila[k++]=(Object)ori.getDescripcion();
                modelo.addRow(fila);
        }    
            
        
        tabletipo_cuenta.setModel(modelo);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cns_tipo_cuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cns_tipo_cuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cns_tipo_cuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cns_tipo_cuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cns_tipo_cuenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabletipo_cuenta;
    private javax.swing.JTextField txtTipo;
    // End of variables declaration//GEN-END:variables
}
