/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.utesa.sistemaoperativo.sistemaarchivos.formularios;

import edu.utesa.sistemaoperativo.sistemaarchivos.Dto.Dto_Persona;
import edu.utesa.sistemaoperativo.sistemaarchivos.Dto.Dto_Cuenta;
import edu.utesa.sistemaoperativo.sistemaarchivos.entidades.Transferencia;
import edu.utesa.sistemaoperativo.sistemaarchivos.entidades.Cuenta;
import edu.utesa.sistemaoperativo.sistemaarchivos.utilidades.Mensajes;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Eduardo Liz
 */
public class mnt_Transferencia1 extends javax.swing.JDialog {

    /**
     * Creates new form mnt_Transferencia1
     */
    
    File file;
    Transferencia transferencia;
    
    public mnt_Transferencia1(javax.swing.JFrame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        transferencia = new Transferencia();
        file = new File(transferencia.getPath_transferencia());
        setNextId();
    }
    
    public mnt_Transferencia1() {
        initComponents();
        transferencia = new Transferencia();
        file = new File(transferencia.getPath_transferencia());
        setNextId();
    }
    
    public int c = 0;
    
    public final void setNextId(){
        ArrayList<Transferencia> list;
        try {
            list = transferencia.getLista(file);
            if(!list.isEmpty())
                txtId.setText(Integer.toString(list.get(list.size()-1).getId_transferencia()+1));
            else
               txtId.setText("1");
            
        } catch (IOException ex) {
            System.err.println("Error leyendo el archivo xxxxxxxxxxxxxxxxxx");
        }
        catch (IndexOutOfBoundsException ex){
            System.err.println("index incorrecto xxxxxxxxxxxxxxxxxxxxx");
        }
    }
    
    public void consultTransferencia(){
        DefaultTableModel modelo = new DefaultTableModel();
        
        String [] cols = {"id","id_cuenta_origen","id_cuenta_destino","id_persona","monto","time","comentario"};
        for (int i=0;i<cols.length;i++)
            modelo.addColumn(cols[i]);
        
        int k;
        ArrayList<Transferencia> list;
        try {
            list = transferencia.getLista(file);
            
            for(Transferencia t : list){
                k=0;
                Object[] fila = new Object[7];
                fila[k++]=(Object)t.getId_transferencia();
                fila[k++]=(Object)t.getId_cuenta_origen();
                fila[k++]=(Object)t.getId_cuenta_destino();
                fila[k++]=(Object)t.getId_persona();
                fila[k++]=(Object)t.getMonto();
                fila[k++]=(Object)t.getTime();
                fila[k++]=(Object)t.getComentario();
                modelo.addRow(fila);
            }
            
        } catch (IOException ex) {
            System.err.println("Error al consultar Persona");
        }
        tableTransferencia.setModel(modelo);
    }
    
    private void cleanTxt(){
        txtCuentaOrigen.setText("");
        txtCuenta.setText("");
        txtIdPersona.setText("");
        txtMonto.setText("");
        txtHora.setText("");
        txtComentario.setText("");
        setNextId();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableTransferencia = new javax.swing.JTable();
        txtId = new javax.swing.JTextField();
        txtMonto = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        txtComentario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCuenta = new javax.swing.JTextField();
        btnElegir = new javax.swing.JButton();
        btnInsertar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtCuentaOrigen = new javax.swing.JTextField();
        btnConsultar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtIdPersona = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        txtHora = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Comentario:");

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton5.setText("...");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        tableTransferencia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tableTransferencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tableTransferenciaMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(tableTransferencia);

        txtId.setEnabled(false);

        jButton10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton10.setText("Salir");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Id_transferencia:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Id_cuenta_origen:");

        txtCuenta.setEnabled(false);

        btnElegir.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnElegir.setText("Elegir");
        btnElegir.setEnabled(false);
        btnElegir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElegirActionPerformed(evt);
            }
        });

        btnInsertar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnInsertar.setText("Insertar");
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Id_cuenta_destino:");

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("...");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setEnabled(false);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Id_persona:");

        txtCuentaOrigen.setEnabled(false);

        btnConsultar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Monto:");

        txtIdPersona.setEnabled(false);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Hora:");

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setText("...");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        txtHora.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));
        txtHora.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtHoraFocusLost(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtComentario)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtCuenta)
                                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(9, 9, 9)
                                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(53, 53, 53)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel4))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtIdPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtCuentaOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 83, Short.MAX_VALUE)))
                                .addGap(30, 30, 30))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtMonto, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                    .addComponent(txtHora))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnElegir)
                        .addGap(34, 34, 34)
                        .addComponent(btnInsertar)
                        .addGap(33, 33, 33)
                        .addComponent(btnEliminar)
                        .addGap(41, 41, 41)
                        .addComponent(btnConsultar)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton10)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCuentaOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(txtCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3)
                    .addComponent(txtIdPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtComentario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnElegir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableTransferenciaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableTransferenciaMouseEntered
        // TODO add your handling code here:
        btnElegir.setEnabled(true);
    }//GEN-LAST:event_tableTransferenciaMouseEntered

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void btnElegirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElegirActionPerformed
        // TODO add your handling code here:
        txtId.setText(tableTransferencia.getModel().getValueAt(tableTransferencia.getSelectedRow(), 0).toString());
        txtCuentaOrigen.setText(tableTransferencia.getModel().getValueAt(tableTransferencia.getSelectedRow(), 1).toString());
        txtCuenta.setText(tableTransferencia.getModel().getValueAt(tableTransferencia.getSelectedRow(), 2).toString());
        txtIdPersona.setText(tableTransferencia.getModel().getValueAt(tableTransferencia.getSelectedRow(), 3).toString());
        txtMonto.setText(tableTransferencia.getModel().getValueAt(tableTransferencia.getSelectedRow(), 4).toString());
        txtHora.setText(tableTransferencia.getModel().getValueAt(tableTransferencia.getSelectedRow(), 5).toString());
        txtComentario.setText(tableTransferencia.getModel().getValueAt(tableTransferencia.getSelectedRow(), 6).toString());

        btnInsertar.setText("Modificar");
        btnEliminar.setEnabled(true);
    }//GEN-LAST:event_btnElegirActionPerformed

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        if(!btnInsertar.getText().equals("Modificar")){
            if(txtHora.getText().isEmpty()){
                Mensajes.mensajeError(evt, "El Formato de hora debe ser el siguiente: hh:mm a");
                return;
            }
            if(!(txtCuentaOrigen.getText().isEmpty() || txtCuenta.getText().isEmpty() || txtIdPersona.getText().isEmpty() || txtMonto.getText().isEmpty() || txtComentario.getText().isEmpty()))
            {
                try {
                    transferencia.add(txtCuentaOrigen.getText(), txtCuenta.getText(), txtIdPersona.getText(), txtMonto.getText(), txtHora.getText(), txtComentario.getText());
                    cleanTxt();
                } catch (IOException ex) {
                    System.err.println("Error de lectura de archivo xxxxxxxxxxxxxxxx ");
                }
            }
            else
            {
                Mensajes.mensajeError(evt, "Debe completar todos los campos!");
            }
        }
        else{
            try {
                System.out.println("Pase por aqui***************");
                transferencia.update(Integer.parseInt(txtId.getText()), txtCuentaOrigen.getText(), txtCuenta.getText(), txtIdPersona.getText(), txtMonto.getText(), txtHora.getText(), txtComentario.getText());
                btnEliminar.setEnabled(false);
                btnInsertar.setText("Insertar");
                cleanTxt();
            } catch (IOException ex) {
                System.err.println("Error de lectura de archivo xxxxxxxxxxxxxxxx ");
            }
        }
        consultTransferencia();        
    }//GEN-LAST:event_btnInsertarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            transferencia.delete(Integer.parseInt(txtId.getText()));
            
        } catch (IOException ex) {
           System.err.println("Error eliminando la persona");
        }
        consultTransferencia();
       
        btnEliminar.setEnabled(false);
        btnInsertar.setText("Insertar");
        cleanTxt();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        // TODO add your handling code here:
        consultTransferencia();
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        c = 1;
        cns_cuenta form = new cns_cuenta(this,true);
        form.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        if(c==1 || c==2){
            if(Dto_Cuenta.getCuenta().getId_cuenta()==0){

            }    
            else{
                if(c==1){
                    txtCuenta.setText(Integer.toString(Dto_Cuenta.getCuenta().getId_cuenta()));
                }
                if(c==2){
                    txtCuentaOrigen.setText(Integer.toString(Dto_Cuenta.getCuenta().getId_cuenta()));
                }  
            }
        }
        
        if(c==3){
            if(Dto_Persona.getPersona().getId_persona() == 0){

            }
            else{
                if(c==3){
                    txtIdPersona.setText(Integer.toString(Dto_Persona.getPersona().getId_persona()));
                }
            }
        }
    }//GEN-LAST:event_formWindowActivated

    private void txtHoraFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtHoraFocusLost
        // TODO add your handling code here:
        if(txtHora.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "El Formato de hora debe ser el siguiente: hh:mm a","Formato de Hora", JOptionPane.INFORMATION_MESSAGE);
            }
        
    }//GEN-LAST:event_txtHoraFocusLost

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        c = 2;
        cns_cuenta form = new cns_cuenta(this,true);
        form.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        c = 3;
        cns_persona form = new cns_persona(this,true);
        form.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mnt_Transferencia1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mnt_Transferencia1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mnt_Transferencia1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mnt_Transferencia1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                mnt_Transferencia1 dialog = new mnt_Transferencia1(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnElegir;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableTransferencia;
    private javax.swing.JTextField txtComentario;
    private javax.swing.JTextField txtCuenta;
    private javax.swing.JTextField txtCuentaOrigen;
    private javax.swing.JFormattedTextField txtHora;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtIdPersona;
    private javax.swing.JTextField txtMonto;
    // End of variables declaration//GEN-END:variables
}
